name: 'Check style pr review'
description: 'Action to run the checkstyle-pr-review tool in a github workflow' 
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  filePath:
    description: "Path to the results file"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'

